openapi: 3.0.0
info:
  title: WASAPhoto API
  version: 1.0.0
  description: WASAPhoto API for our university course on web and software architecture
tags:
  - name: login
  - name: user
  - name: comment
  - name: like
  - name: photo
  
security:
  - BearerAuth: []
  
  
paths:
  /session:
    post:
      tags: [login]
      summary: Logs in the user
      description: |
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: User's name
                  minLength: 3
                  maxLength: 50
                  pattern: "^[a-zA-Z0-9_]+$"  # Add a pattern for every string property
              description: General user object
                  
          
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User' # Add a pattern for every string property
                    
                

  /users/:
    post:
      tags: [user]
      summary: Create User
      description: Create a new user.
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'

      responses:
        '201':
          description: User created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        '401':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

                
                
    
  /users/{username}/banned/:
    parameters:
        - name: username
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/username'
    post:
      tags: [user]
      summary: Ban User
      description: Ban a user.
      operationId: banUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: '#/components/schemas/username'
              description: the user id of the banned user
      responses:
        '201':
          description: User banned successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                    maxLength: 200
                    pattern: "^[a-zA-Z0-9_]+$"
                    description: Returing a message about what user is banned
                description: The output for banning a user
  
        '401':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
    delete:
      tags: [user]
      summary: Unban User
      description: Unban a user.
      operationId: unbanUser
  
      responses:
        '200':
          description: User unbanned successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                    maxLength: 200
                    pattern: "^[a-zA-Z0-9_]+$"
                    description: telling the user it worked
                description: the response for unbanning a user
  
        '401':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /stream:
    get:
      tags: [user]
      summary: Get My Stream
      description: Retrieve the user's stream.
      operationId: getMyStream
      
  
      responses:
        '200':
          description: User's stream retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  stream:
                    type: array
                    items:
                      $ref: '#/components/schemas/PhotoDetails'
                    minItems: 0
                    maxItems: 100
                    description: a photo detail object in the users stream
                description: The entire stream of photos

        '403':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'             
  /users/{username}:
    patch:
      tags: [user]
      summary: Set My User Name
      description: Set the user's username.
      operationId: setMyUserName
      parameters:
        - name: username
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/username'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'

      responses:
        '201':
          description: User's username updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        '401':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'            
  
    get:
      tags: [user]
      summary: Get User Profile
      description: Get the profile of a user.
      operationId: getUserProfile
      parameters:
        - name: username
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/username'

      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        '403':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
                
                
                
  /users/{username}/followers/:
    parameters:
          - name: username
            in: path
            required: true
            schema:
              $ref: '#/components/schemas/username'
            description: the id of the user
    post:
      tags: [user]
      summary: Follow User
      description: Follow a user.
      operationId: followUser
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: '#/components/schemas/username'
              description: follow confirmation

      responses:
        '201':
          description: User followed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                    maxLength: 200
                    pattern: "^[a-zA-Z0-9_]+$"
                    description: the success message
                description: The general response to following

        '401':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags: [user]
      summary: Unfollow User
      description: Unfollow a user.
      operationId: unfollowUser
      responses:
        '200':
          description: User unfollowed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                    maxLength: 200
                    pattern: "^[a-zA-Z0-9_]+$"
                    description: unfollow message
                description: The response to unfollowing

        '401':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /photos/{photoId}/comments/:
    post:
      tags: [comment]
      summary: Comment on Photo
      description: Comment on a photo.
      parameters:
        - name: photoId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/photo_id'
      operationId: commentPhoto

      responses:
        '201':
          description: Comment added to the photo successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                    maxLength: 200
                    pattern: "^[a-zA-Z0-9_]+$"
                    description: the message
                description: the object returned

        '401':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /comments/{commentId}:
    delete:
      tags: [comment]
      summary: Remove Comment from Photo
      description: Remove a comment from a photo.
      operationId: uncommentPhoto
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: string
            minLength: 10
            maxLength: 20
            pattern: "^[a-zA-Z0-9_]+$"
            description: The comment ID

      responses:
        '200':
          description: Comment removed from the photo successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                    maxLength: 200
                    pattern: "^[a-zA-Z0-9_]+$"
                    description: Telling the user you removed the comment
                description: The entire response

        '401':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /photos/{photoId}/like:
    post:
      tags: [like, photo]
      summary: Like Photo
      description: Like a photo.
      operationId: likePhoto
      parameters:
        - name: photoId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/photo_id'


      responses:
        '201':
          description: Photo liked successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                    maxLength: 200
                    pattern: "^[a-zA-Z0-9_]+$"
                    description: telling the user he liked
                description: the entire response

        '401':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


     

  /likes/{likeId}:
    delete:
      tags: [like]
      summary: Unlike Photo
      description: Unlike a photo.
      operationId: unlikePhoto
      parameters:
        - name: likeId
          in: path
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z0-9]{10,20}$' 
            minLength: 10
            maxLength: 100 # Pattern added
            description: unique like id
      responses:
        '200':
          description: Photo unliked successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                    maxLength: 200
                    pattern: '^[a-zA-Z0-9]{10,20}$'
                    description: saying you unliked correctly
                description: response to unliking

        '401':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/{username}/photos/:
    post:
      tags: [photo]
      summary: Upload Photo
      description: Upload a photo.
      operationId: uploadPhoto
      parameters:
        - name: username
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/username'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Photo'
      responses:
        '201':
          description: Photo uploaded successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  photoId:
                    $ref: '#/components/schemas/photo_id'
                description: The response to uploading a photo succesfuly
                

        '401':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /photos/{photoId}:
    delete:
      tags: [photo]
      summary: Delete Photo
      description: Delete a photo.
      operationId: deletePhoto
      parameters:
        - name: photoId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/photo_id'
      responses:
        '200':
          description: Photo deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                    maxLength: 200
                    pattern: '^[a-zA-Z0-9]{10,20}$'
                    description: You uploaded succesfully
                description: Response to upload succesfully

        '401':
          description: Unauthorized. User authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          minLength: 1
          maxLength: 200
          pattern: '^[a-zA-Z0-9]{10,20}$'
          description: Describes the more specific error I am putting out
      description: The overall error object
      
    User:
      type: object
      properties:
        username:
          type: string
          minLength: 4
          maxLength: 30
          pattern: "^[a-zA-Z0-9_]+$"
          description: User's username
        Following:
          type: integer
          minimum: 0
          maximum: 1000000
          description: The number of followers the user has
        Followers:
          type: integer
          minimum: 0
          description: The number of people the user is following
        PhotosCount:
          type: integer
          minimum: 0
          maximum: 1000000
          description: The number of images the user has posted
        Photos:
          type: array
          items:
            $ref: '#/components/schemas/Photo'
          description: List of photos posted by the user
      description: The entire user with all its attributes
          
    Photo:
      type: object
      properties:
        username:
          type: string
          minLength: 10
          maxLength: 20
          pattern: '^[a-zA-Z0-9_]+$'
          description: A unique username of the poster
        photo_id:
          type: integer
          minimum: 0
          maximum: 100000
          description: A unique photo identifier
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the photo was posted
        image_data:
          type: string
          description: Base64-encoded image data
          minLength: 50
          maxLength: 500000
          pattern: '^[0-1]+$'
          example: '00010101010011111010001001010100010101010100100101010101010001000101010100011110101010101010001010110010101010100101001010101010101010101010010010101010101010101011100001010101101010101110101010111001010111000010101010001011010101110'
      required:
        - imageData
      description: the photo object
    
    photo_id:
      type: string
      minLength: 10
      maxLength: 20
      pattern: '^[a-zA-Z0-9_]+$'
      description: A unique photo identifier

      
    username:
          type: string
          minLength: 10
          maxLength: 20
          pattern: "^[a-zA-Z0-9_]+$"
          description: A unique user identifier
    PhotoDetails:
      type: object
      properties:
        username:
          type: string
          description: Username of the user who posted the photo
        photoId:
          type: string
          description: Unique identifier of the photo
        imageData:
          type: string
          format: byte
          description: Base64-encoded image data
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the photo was uploaded
        likesCount:
          type: integer
          description: Number of likes on the photo
        commentsCount:
          type: integer
          description: Number of comments on the photo
      description: An information schema about a photo which doesnt have to be stored
      
    
      
          
          

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 